name: Flatter
description: Build and distribute Flatpak applications
author: Andy Holmes
branding:
  icon: package
  color: blue
inputs:
  files:
    description: >
      A list of paths to Flatpak manifests.
    required: true
  cache-key:
    description: >
      An optional cache key.
    default: 'flatter'
    required: false
  upload-pages-artifact:
    description: >
      Upload the repository as a GitHub Pages Artifact.
    default: false
    required: false
  upload-flatpak-bundle:
    description: >
      Upload each application as a Flatpak bundle.
    default: false
    required: false

  # Command-line Options
  arch:
    description: >
      The CPU architecture to build for.
    default: x86_64
    required: false
  default-branch:
    description: >
      The Flatpak default branch.
    required: false
  gpg-sign:
    description: >
      The fingerprint of the GPG key sign te repository with.
    required: false
  gpg-homedir:
    description: >
      A path to search for GPG keys.
    required: false
  gpg-keys:
    description: >
      A path to load GPG keys.
    required: false
  install-deps-from:
    description: >
      The remote to install build dependencies from.
    required: false
  repo:
    description: >
      The folder used to store Flatpak repository files.
    default: repo
    required: false
runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
  post-if: 'success()'
