# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2022 Andy Holmes <andrew.g.r.holmes@gmail.com>

name: Flatter
description: Build and distribute Flatpak applications
author: Andy Holmes
branding:
  icon: package
  color: blue
inputs:
  files:
    description: >
      A list of paths to Flatpak manifests.
    required: true
  upload-flatpak-bundle:
    description: >
      Upload each application as a Flatpak artifact.
    default: false
    required: false
  upload-pages-artifact:
    description: >
      Upload the repository as a GitHub Pages artifact.
    default: false
    required: false
  flatpakrepo:
    description: >
      Include a generated .flatpakrepo file in the repository.
    default: true
    required: false
  include-files:
    description: >
      Extra files to include in the repository.
    required: false
  cache-key:
    description: >
      An optional cache key.
    default: 'flatter'
    required: false

  # Command-line Options
  arch:
    description: >
      The CPU architecture to build for.
    default: x86_64
    required: false
  gpg-sign:
    description: >
      The fingerprint of a GPG key to sign the repository with.
    required: false
  repo:
    description: >
      The folder used to store Flatpak repository files.
    default: repo
    required: false
  flatpak-builder-args:
    description: >
      Extra command-line options for `flatpak-builder`.
    required: false
  flatpak-build-bundle-args:
    description: >
      Extra command-line options for `flatpak build-bundle`.
    required: false
runs:
  using: node16
  main: dist/index.js
