# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2022 Andy Holmes <andrew.g.r.holmes@gmail.com>

name: Flatter
description: Build and distribute Flatpak applications
author: Andy Holmes
branding:
  icon: package
  color: blue
inputs:
  files:
    description: >
      A list of paths to Flatpak manifests.
    required: true
  arch:
    description: >
      The CPU architecture to build for.
    default: x86_64
    required: false
  gpg-sign:
    description: >
      The fingerprint of a GPG key to sign the repository with.
    required: false
  repo:
    description: >
      The folder used to store Flatpak repository files.
    default: repo
    required: false
  cache-key:
    description: >
      An optional cache key.
    default: 'flatter'
    required: false

  # Deployment Options
  upload-bundles:
    description: >
      Upload each application as an artifact.
    default: false
    required: false
  upload-pages-artifact:
    description: >
      Upload the repository as a GitHub Pages artifact.
    default: false
    required: false
  include-files:
    description: >
      A list of extra files to include in the GitHub Pages artifact.
    required: false

  # Test Options
  run-tests:
    description: >
      Build and run tests in a Flatpak environment.
    required: false
    default: false
  test-config-opts:
    description: >
      Extra command-line options for `meson setup`
    required: false
  test-modules:
    description: >
      Path to a manifest of dependencies, relative to the root manifest.
    required: false

  # Advanced Options
  flatpak-builder-args:
    description: >
      Extra command-line options for `flatpak-builder`.
    required: false
  flatpak-build-bundle-args:
    description: >
      Extra command-line options for `flatpak build-bundle`.
    required: false
runs:
  using: node16
  main: dist/index.js
