# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: No rights reserved

version = 1

[[annotations]]
path = [".eslintrc.json", ".github/**", ".gitignore", "tests/**", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "No rights reserved"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["dist/**", "package.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Andy Holmes <andrew.g.r.holmes@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
