name: Container Registry

on:
  push:
    branches: [main]
    paths: [Dockerfile]
  pull_request:
    branches: [main]
    paths: [Dockerfile]
  schedule:
    # Once a week
    - cron: "0 0 * * */7"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000

    strategy:
      matrix:
        include:
          - platform: freedesktop
            packages: org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
            remote: flathub
            version: 21.08
            arch: x86_64

          - platform: freedesktop
            packages: org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08
            remote: flathub
            version: 21.08
            arch: aarch64

          - platform: freedesktop
            packages: org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
            remote: flathub
            version: 22.08
            arch: x86_64

          - platform: freedesktop
            packages: org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
            remote: flathub
            version: 22.08
            arch: aarch64

          - platform: gnome
            packages: org.gnome.Platform//43 org.gnome.Sdk//43
            remote: flathub
            version: 43
            arch: x86_64

          - platform: gnome
            packages: org.gnome.Platform//43 org.gnome.Sdk//43
            remote: flathub
            version: 43
            arch: aarch64

          - platform: gnome
            packages: org.gnome.Platform//44 org.gnome.Sdk//44
            remote: flathub
            version: 44
            arch: x86_64

          - platform: gnome
            packages: org.gnome.Platform//44 org.gnome.Sdk//44
            remote: flathub
            version: 44
            arch: aarch64

          - platform: gnome
            packages: org.gnome.Platform//master org.gnome.Sdk//master
            remote: gnome-nightly
            version: master
            arch: x86_64

          - platform: gnome
            packages: org.gnome.Platform//master org.gnome.Sdk//master
            remote: gnome-nightly
            version: master
            arch: aarch64
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Base Image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: Dockerfile
          pull: true
          push: true
          tags: localhost:5000/flatter-base:latest

      - name: Generate Dockerfile
        run: |
          cat >> ${{ matrix.platform }}.Dockerfile << EOF
          # syntax = docker/dockerfile:experimental
          FROM localhost:5000/flatter-base:latest

          RUN --security=insecure flatpak install -y \
                                                  --arch=${{ matrix.arch }} \
                                                  --noninteractive \
                                                  ${{ matrix.remote }} \
                                                  ${{ matrix.packages }}
          EOF

      - name: Build
        uses: docker/build-push-action@v4
        with:
          allow: security.insecure
          context: .
          file: ${{ matrix.platform }}.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/andyholmes/flatter/${{ matrix.arch }}/${{ matrix.platform }}:${{ matrix.version }}
