name: Code Scanning
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spell Check
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,dist

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Build
      uses: github/codeql-action/autobuild@v3

    - name: Analyze
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        uses: wagoid/commitlint-github-action@v5

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Analyze
        run: npx eslint .
          --config .eslintrc.json
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  dependency-review:
    if: ${{ github.event_name == 'pull_request' }}
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Review
        uses: actions/dependency-review-action@v3

  reuse:
    name: REUSE Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        uses: fsfe/reuse-action@v2
        with:
          args: lint
